[project]
name = "food-cam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "instagrapi>=2.1.3",
    "pillow>=11.0.0",
]
